// Default categories. Colors follow the dashboard's categorical palette.
export const SEED_CATEGORIES: { name: string; color: string }[] = [
  { name: "Groceries", color: "#008300" },
  { name: "Dining & Cafés", color: "#eb6834" },
  { name: "Shopping", color: "#4a3aa7" },
  { name: "Subscriptions & Media", color: "#e34948" },
  { name: "Transport", color: "#2a78d6" },
  { name: "Travel", color: "#1baf7a" },
  { name: "Health & Fitness", color: "#d55181" },
  { name: "Housing & Utilities", color: "#6b4f36" },
  { name: "Insurance", color: "#52514e" },
  { name: "Entertainment", color: "#c98500" },
  { name: "Fees & Interest", color: "#898781" },
  { name: "Income & Refunds", color: "#006300" },
];

// Keyword patterns (uppercase, contains-match against normalized merchant).
// Tuned for German + international credit card statements.
export const SEED_RULES: Record<string, string[]> = {
  Groceries: [
    "COOP",
    "MIGROS",
    "DENNER",
    "VOLG",
    "SPAR DANKT",
    "LANDI",
    "REWE",
    "EDEKA",
    "ALDI",
    "LIDL",
    "PENNY",
    "KAUFLAND",
    "NETTO",
    "DM ",
    "DM-",
    "DROGERIE",
    "ROSSMANN",
    "SUPERMARKT",
    "TEGUT",
    "GLOBUS",
    "HIT ",
    "NORMA",
  ],
  "Dining & Cafés": [
    "MCDONALD",
    "BURGER KING",
    "KFC",
    "SUBWAY",
    "LIEFERANDO",
    "UBER EATS",
    "WOLT",
    "DELIVEROO",
    "RESTAURANT",
    "PIZZERIA",
    "PIZZA",
    "CAFE",
    "COFFEE",
    "STARBUCKS",
    "BAECKEREI",
    "BACKEREI",
    "BAKERY",
    "IMBISS",
    "BISTRO",
    "SUSHI",
    "DOENER",
  ],
  Shopping: [
    "ALIEXPRESS",
    "AMAZON",
    "AMZN",
    "ZALANDO",
    "IKEA",
    "MEDIA MARKT",
    "MEDIAMARKT",
    "SATURN",
    "OTTO",
    "H&M",
    "H & M",
    "ZARA",
    "TEMU",
    "SHEIN",
    "EBAY",
    "ETSY",
    "DECATHLON",
    "OBI",
    "BAUHAUS",
    "HORNBACH",
    "TK MAXX",
    "C&A",
  ],
  "Subscriptions & Media": [
    "NETFLIX",
    "SPOTIFY",
    "DISNEY",
    "PRIME VIDEO",
    "AMAZON PRIME",
    "YOUTUBE",
    "ICLOUD",
    "APPLE.COM/BILL",
    "APPLE SERVICES",
    "GOOGLE ONE",
    "GOOGLE STORAGE",
    "AUDIBLE",
    "DAZN",
    "WOW ",
    "PARAMOUNT",
    "ADOBE",
    "MICROSOFT 365",
    "DROPBOX",
    "PATREON",
    "ABO",
  ],
  Transport: [
    "SOCAR",
    "MIGROL",
    "AVIA ",
    "TAMOIL",
    "AGROLA",
    "SBB",
    "TESLA",
    "SHELL",
    "ARAL",
    "ESSO",
    "TOTAL",
    "JET ",
    "AGIP",
    "TANKSTELLE",
    "TANK",
    "DEUTSCHE BAHN",
    "DB BAHN",
    "DB VERTRIEB",
    "BAHN.DE",
    "FLIXBUS",
    "FLIXTRAIN",
    "UBER",
    "BOLT",
    "FREENOW",
    "TAXI",
    "MVG",
    "HVV",
    "BVG",
    "RMV",
    "VRR",
    "PARKEN",
    "PARKING",
    "PARKHAUS",
    "SIXT",
    "MILES",
    "SHARENOW",
  ],
  Travel: [
    "LUFTHANSA",
    "RYANAIR",
    "EUROWINGS",
    "EASYJET",
    "CONDOR",
    "BOOKING",
    "AIRBNB",
    "HOTEL",
    "HOSTEL",
    "EXPEDIA",
    "TRIVAGO",
    "OPODO",
    "TUI",
  ],
  "Health & Fitness": [
    "AMAVITA",
    "APOTHEKE",
    "PHARMACY",
    "MCFIT",
    "FITX",
    "FITNESS",
    "URBAN SPORTS",
    "GYM",
    "ZAHNARZT",
    "ARZT",
    "PRAXIS",
    "OPTIKER",
    "FIELMANN",
  ],
  "Housing & Utilities": [
    "STADTWERKE",
    "VATTENFALL",
    "E.ON",
    "EON",
    "ENBW",
    "RHEINENERGIE",
    "TELEKOM",
    "VODAFONE",
    "O2 ",
    "TELEFONICA",
    "1&1",
    "1UND1",
    "PYUR",
    "MIETE",
    "RUNDFUNK",
    "STROM",
    "GAS ",
  ],
  Insurance: [
    "ALLIANZ",
    "HUK",
    "AXA",
    "ERGO",
    "VERSICHERUNG",
    "INSURANCE",
    "SIGNAL IDUNA",
    "DEBEKA",
    "GETSAFE",
  ],
  Entertainment: [
    "KINO",
    "CINEMA",
    "CINEMAXX",
    "UCI",
    "STEAM",
    "PLAYSTATION",
    "NINTENDO",
    "XBOX",
    "EVENTIM",
    "TICKETMASTER",
    "THALIA",
    "HUGENDUBEL",
    "MUSEUM",
    "THEATER",
  ],
  "Fees & Interest": [
    "ENTGELT",
    "GEBUEHR",
    "GEBUHR",
    "KONTOFUEHRUNG",
    "ZINSEN",
    "AUSLANDSEINSATZ",
    "FEE",
    "INTEREST",
    "CHARGE",
    "JAHRESPREIS",
  ],
  "Income & Refunds": [
    "GUTSCHRIFT",
    "ERSTATTUNG",
    "REFUND",
    "CASHBACK",
    "RUECKZAHLUNG",
    "AUSGLEICH",
    "LOHN",
    "GEHALT",
  ],
};
